src/index.tsx, src/pages/Project/Create.tsx, src/pages/Project/CreateBlank.tsx, src/pages/Project/CreateTemplate.tsx, src/pages/Project/ProjectDetailPage.tsx, src/pages/Project/ProjectPage.tsx, src/utils/i18n/translations/ko.json, src/utils/service-utils.ts
일단 모양만 만들었습니다. 서비스콜이 업데이트 되면 적용하겠습니다
=> [feat] create template 페이지 구성, create CI/CD 모달 구성 완료

src/components/Loading/LoadingScreen.tsx, src/pages/Project/CreateBlank.tsx, src/pages/Project/ProjectDetailPage.tsx, src/pages/Project/ProjectPage.tsx, src/stores/indexStore.ts, src/stores/loadingStore.ts, src/style.css, src/utils/service-utils.ts
=> [feat]데이터 보내고 받을 때까지 로딩애니메이션 구현

src/components/GNB/EditorGNB.tsx, src/index.tsx, src/pages/Project/ProjectDetailPage.tsx, src/utils/SmallIcon.tsx
프로젝트 디테일 페이지 레퍼런스 바꿀 때 url변경, 페이지 처음 들어갈때 레퍼런스 선택된채로 들어가기, 중복 코드 분리하여 간소화, 코드 보기 쉽게 정리, New Folder 액션 오류 수정
=> [feat]프로젝트 디테일 페이지 레퍼런스 바꿀 때 url변경, 페이지 처음 들어갈때 레퍼런스 선택된채로 들어가기 등등

src/pages/Project/FileTreeView.tsx, src/pages/Project/ProjectPage.tsx
전체 페이지가 새로고침되어 SPA를 활용하지 못했던코드 수정 및 코드 정리
=> [feat] 전체 페이지가 새로고침되어 SPA를 활용하지 못했던코드 수정

src/pages/Project/ProjectPage.tsx, src/utils/TablePage.tsx
=> [feat] 테이블 컴포넌트를 공용 유틸 컴포넌트로 만들어서 사용, 페이지 네이션 기능 추가

src/components/LNB/SCM/SCM.tsx, src/utils/service-utils.ts
commit 이후 자동으로 commit list 다시 받기
scm lnb 정리
=> [feat][patch] after commit refresh and scm refact

src/components/Editor/Editor.tsx, src/components/LNB/SourceCodeTree.tsx, src/stores/editorContentsStore.ts, src/stores/folderTreeStore.ts, src/stores/workspaceStore.ts
- file delete, folder add 기능 추가 및 코드 리펙토링(모나코 에디터 content 저장방식 등)
- rename 기능은 commit 시 서버에 전송하는 방식에 문제가 있다고 판단되어 임시 제거
=> [feat] file delete, folder add 기능 추가 및 코드 리펙토링

script/run.sh, src/components/Editor/CustomTab.tsx, src/components/GNB/GNBDialog.tsx, src/components/GNB/ImportDirectoryDialog.tsx, src/components/GNB/ImportFileDialog.tsx, src/components/LNB/SourceCodeTree.tsx, src/language-service/ast.ts, src/language-service/language-service.ts, src/language-service/type-ast-visitor.ts, src/pages/Project/FileTreeView.tsx, src/pages/Project/ProjectDetailPage.tsx, src/pages/Project/ProjectPage.tsx
=> [feat] 타입지정 및 코드 리팩토링

src/pages/Project/CommitHistory.tsx, src/pages/Project/CreateTemplate.tsx, src/pages/Project/ProjectDetailPage.tsx, src/stores/workspaceStore.ts, src/utils/alert-utils.ts, src/utils/service-utils.ts
CI/CD create 서비스 연결 및 create tem 서비스연결 및 로딩 구조 리팩토링하였습니다
=> [feat] CI/CD create 서비스 연결 및 create tem 서비스연결 및 로딩 구조 리팩토링

src/components/Editor/EditorStatusBar.tsx, src/pages/Editor/EditorPage.tsx, src/style.css
=> [feat][patch]editor status bar 추가

src/pages/Project/CreateTemplate.tsx, src/pages/Project/ProjectDetailPage.tsx
=> [feat] template 프로젝트 생성페이지 기획과 다른 부분 수정

src/pages/CICD/CICDListPage.tsx, src/pages/CICD/CICDModal.tsx, src/pages/Project/ProjectDetailPage.tsx, src/style.css, src/utils/TablePage.tsx
=> [feat] Table Header CI/CD Create Button Reference Select CI/CD Create Modal List Page Link Project CI/CD Report Modal button

src/index.tsx, src/pages/CICD/CICDDetailPage.tsx, src/style.css, src/utils/service-utils.ts
=> [feat]CI/CD Report Detail Page 추가

src/pages/CICD/CICDDetailPage.tsx
CI/CD report detail 늦게 반영되는 문제 해결했습니다.
=> [bugfix] CI/CD Detail Page Status 늦게 뜨는 버그 수정

src/components/GNB/GNB.tsx, src/index.tsx, webpack.config.js
[feat]add select project dialog
기획에 있던 기능 추가해봤습니다.
따로 commit 하려고 했는데 base path 변경 기능 추가 급하게 하려다 보니 같이 하게되었습니다.
[feat] base path 변경
superpx standalone 이미지에서는 /px/index.html 로 접속하게 하기 위해서 base path 변경함
=> [feat] base path 변경

src/components/Form/CreateReferenceForm.tsx, src/components/GNB/GNB.tsx, src/pages/CICD/CICDDetailPage.tsx, src/pages/CICD/CICDListPage.tsx, src/pages/CICD/CICDModal.tsx, src/pages/Group/GroupPage.tsx, src/pages/Project/CommitHistory.tsx, src/pages/Project/Create.tsx, src/pages/Project/CreateBlank.tsx, src/pages/Project/CreateTemplate.tsx, src/pages/Project/FileTreeView.tsx, src/pages/Project/ProjectDetailPage.tsx, src/pages/Project/ProjectPage.tsx
[feat] create ref 소스 ref 추가 할수있도록 수정 하였습니다
[feat] /px 라우팅 수정
=> [feat] create ref 소스 ref 추가 할수있도록 수정, /px 라우팅 수정

webpack.config.js
=> [bugfix]새로고침시 생기는 오류 수정

CHANGELOG/tag.txt, src/components/GNB/GNB.tsx, src/index.tsx, src/pages/CICD/CICDDetailPage.tsx, src/pages/CICD/CICDListPage.tsx, src/pages/CICD/CICDModal.tsx, src/pages/Group/GroupPage.tsx, src/pages/Project/CommitHistory.tsx, src/pages/Project/Create.tsx, src/pages/Project/CreateBlank.tsx, src/pages/Project/CreateTemplate.tsx, src/pages/Project/FileTreeView.tsx, src/pages/Project/ProjectDetailPage.tsx, src/pages/Project/ProjectPage.tsx, webpack.config.js
=> [feat] px 라우트 제거

src/components/GNB/GNBDialog.tsx, src/components/GNB/ImportDirectoryDialog.tsx, src/components/GNB/ImportFileDialog.tsx
[feat] 오타 수정
cancle 오타 수정
[bugfix][patch][IMS 302156] [PX] 폴더, 파일 import 시 소스들이 editor 화면에 모두 열림
파일 import 시 editor store update 제거
=> [feat] 오타 수정, [bugfix][patch][IMS 302156] [PX] 폴더, 파일 import 시 소스들이 editor 화면에 모두 열림

src/pages/Project/ProjectDetailPage.tsx
=> [feat][patch] 프로젝트 디테일 페이지 add file 알고리즘 수정

src/components/GNB/GNB.tsx, src/index.tsx, src/pages/Editor/EditorPage.tsx, src/stores/workspaceStore.ts
=> [feat][patch][IMS 302171] 상단 select project에서 project 변경 시 메인페이지로 이동하는 현상

src/pages/Project/ProjectDetailPage.tsx
프로젝트에서 뒤로가기 버튼 눌렀을 때 project 리스트 조회화면으로 돌아가도록 수정
=> [feat][patch][IMS 302187] 프로젝트에서 뒤로가기 버튼 눌렀을 때 project 리스트 조회화면으로 돌아가도록 수정

src/pages/Project/CreateBlank.tsx, src/pages/Project/CreateTemplate.tsx
=> [feat][patch][IMS 302273]project 생성 시 변수 값 입력에 따른 생성 버튼 비활성화 유무 변경 요청

src/pages/CICD/CICDModal.tsx
Target Master SAS IP 문구 변경하였습니다
=> [feat][patch]Target Master SAS IP 문구 변경

src/components/Form/CreateReferenceForm.tsx
create 버튼 비활성화 조건추가
reference 이름 없을때,
source reference 선택 안되었을때,
reference main 이 있으면 source reference 초기값으로 main 추가
=> [feat][patch][IMS 302371]브랜치 생성 시 source reference name이 비어있는 경우 create 버튼 비활성화 되거나 default로 main 브랜치 선택 되도록 수정 요청
